---
- hosts: all
  become: true
  tasks:
    - name: install apache2
      apt: 
        name=apache2 update_cache=yes state=latest
      
#In our case creating the environment means that the packages are updated and java is installed. These are defined in the role common :
    - name: Ensure kernel is at the latest version
      yum: name=kernel state=latest

    - name: Install latest Java 8
      yum: name=java-1.8.0-openjdk.x86_64 state=latest
      
# https://ansible.github.io/workshops/exercises/ansible_rhel/1.3-playbook/

    - name: Apache server installed
      hosts: web
      become: yes
      tasks:
    - name: latest Apache version installed
      yum:
        name: httpd
        state: latest
    - name: Apache enabled and running
      service:
        name: httpd
        enabled: true
        state: started
    - name: copy web.html
      copy:
        src: web.html
        dest: /var/www/html/index.html
